name: build-image

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 1'

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 360
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: Build image
        run: |
          PIGEN_DOCKER_OPTS="-e WORK_DIR=/mnt/work" ./build.sh

      - name: Upload image
        uses: actions/upload-artifact@v7
        with:
          name: raspios-lite-ansible
          path: pi-gen/deploy/*.img.xz
          retention-days: 14
